// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WatchManageStore.Data;

namespace WatchManageStore.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20220330024236_CreateDBNew")]
    partial class CreateDBNew
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityUser");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("WatchManageStore.Models.Brand", b =>
                {
                    b.Property<int>("BrandId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BrandName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BrandId");

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            BrandId = 1,
                            BrandName = "Đồng hồ Philippe Auguste",
                            Image = "thuong-hieu2.png"
                        },
                        new
                        {
                            BrandId = 2,
                            BrandName = "Đồng hồ Diamond D",
                            Image = "thuong-hieu3.png"
                        },
                        new
                        {
                            BrandId = 3,
                            BrandName = "Thương hiệu Bovet",
                            Image = "thuong-hieu4.png"
                        },
                        new
                        {
                            BrandId = 4,
                            BrandName = "Thương hiệu Jacques Lemans",
                            Image = "thuong-hieu5.png"
                        },
                        new
                        {
                            BrandId = 5,
                            BrandName = "Thương hiệu Aries Gold",
                            Image = "thuong-hieu6.png"
                        },
                        new
                        {
                            BrandId = 6,
                            BrandName = "Thương hiệu Q&Q",
                            Image = "thuong-hieu6.png"
                        },
                        new
                        {
                            BrandId = 7,
                            BrandName = "Thương hiệu Atlantic Swiss",
                            Image = "thuong-hieu7.png"
                        },
                        new
                        {
                            BrandId = 8,
                            BrandName = "Thương hiệu Hublot",
                            Image = "thuong-hieu8.png"
                        },
                        new
                        {
                            BrandId = 9,
                            BrandName = "Thương hiệu Epos Swiss",
                            Image = "thuong-hieu9.png"
                        },
                        new
                        {
                            BrandId = 10,
                            BrandName = "Thương hiệu Bruno Sohnle Glashutte",
                            Image = "thuong-hieu4.png"
                        });
                });

            modelBuilder.Entity("WatchManageStore.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CategoryName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Đồng hồ nam"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Đồng hồ nữ"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Đồng hồ đôi"
                        });
                });

            modelBuilder.Entity("WatchManageStore.Models.Comment", b =>
                {
                    b.Property<int>("CommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PostId")
                        .HasMaxLength(50)
                        .HasColumnType("int");

                    b.Property<bool>("Publish")
                        .HasColumnType("bit");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("WatchId")
                        .HasColumnType("int");

                    b.HasKey("CommentId");

                    b.HasIndex("Id");

                    b.HasIndex("PostId");

                    b.HasIndex("WatchId");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            CommentId = 1,
                            Content = "Tất cả các sản phẩm trên thị trường đều có điểm tốt và hạn chế. Do đó để viết bài review hiệu quả bạn cần nhớ KHÔNG CÓ GÌ LÀ HOÀN HẢO!",
                            CreateOn = new DateTime(2022, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifyDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PostId = 3,
                            Publish = true,
                            UserId = "408aa945-3d84-4421-8342-7269ec64d949"
                        },
                        new
                        {
                            CommentId = 2,
                            Content = "Nhưng bạn cần viết nhiều hơn về lợi ích, ví dụ như nó giúp người dùng tự tin hơn trong giao tiếp, nâng cao chất lượng sống, giảm nguy cơ mắc bệnh tim mạch, tiểu đường… Lợi ích của sản phẩm sẽ có hiệu quả tốt hơn khi bạn muốn thuyết phục khách hàng!",
                            CreateOn = new DateTime(2022, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifyDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PostId = 2,
                            Publish = true,
                            UserId = "408aa945-3d84-4421-8342-7269ec64d949"
                        });
                });

            modelBuilder.Entity("WatchManageStore.Models.DetailWatch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Diameter")
                        .HasColumnType("int");

                    b.Property<string>("Facematerial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Style")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Warranty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WatchID")
                        .HasColumnType("int");

                    b.Property<bool>("Waterproof")
                        .HasColumnType("bit");

                    b.Property<string>("WireMaterial")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("WatchID")
                        .IsUnique();

                    b.ToTable("DetailWatchs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Diameter = 36,
                            Facematerial = "Sapphire mặt trong đính 4 viên kim cương cọc số",
                            Style = "Đồng hồ nữ",
                            WatchID = 1,
                            Waterproof = true,
                            WireMaterial = "Dây da chính hãng kèm 1 dây Silver gold ( vàng trắng )"
                        },
                        new
                        {
                            Id = 2,
                            Diameter = 40,
                            Facematerial = "Sapphire mặt trong đính 4 viên kim cương cọc số",
                            Style = "Đồng hồ nam",
                            WatchID = 2,
                            Waterproof = true,
                            WireMaterial = "Dây da chính hãng kèm 1 dây Silver gold ( vàng trắng )"
                        },
                        new
                        {
                            Id = 3,
                            Diameter = 40,
                            Facematerial = "Sapphire mặt trong đính 4 viên kim cương cọc số",
                            Style = "Đồng hồ nam",
                            WatchID = 3,
                            Waterproof = true,
                            WireMaterial = "Dây da chính hãng kèm 1 dây Silver gold ( vàng trắng )"
                        },
                        new
                        {
                            Id = 4,
                            Diameter = 40,
                            Facematerial = "Sapphire mặt trong đính 4 viên kim cương cọc số",
                            Style = "Đồng hồ nam",
                            WatchID = 4,
                            Waterproof = true,
                            WireMaterial = "Dây da chính hãng kèm 1 dây Silver gold ( vàng trắng )"
                        },
                        new
                        {
                            Id = 5,
                            Diameter = 40,
                            Facematerial = "Sapphire mặt trong đính 4 viên kim cương cọc số",
                            Style = "Đồng hồ nam",
                            WatchID = 5,
                            Waterproof = true,
                            WireMaterial = "Dây da chính hãng kèm 1 dây Silver gold ( vàng trắng )"
                        },
                        new
                        {
                            Id = 6,
                            Diameter = 40,
                            Facematerial = "Sapphire mặt trong đính 4 viên kim cương cọc số",
                            Style = "Đồng hồ nam",
                            WatchID = 6,
                            Waterproof = true,
                            WireMaterial = "Dây da chính hãng kèm 1 dây Silver gold ( vàng trắng )"
                        },
                        new
                        {
                            Id = 7,
                            Diameter = 40,
                            Facematerial = "Sapphire mặt trong đính 4 viên kim cương cọc số",
                            Style = "Đồng hồ nam",
                            WatchID = 7,
                            Waterproof = true,
                            WireMaterial = "Dây da chính hãng kèm 1 dây Silver gold ( vàng trắng )"
                        },
                        new
                        {
                            Id = 8,
                            Diameter = 40,
                            Facematerial = "Sapphire mặt trong đính 4 viên kim cương cọc số",
                            Style = "Đồng hồ nam",
                            WatchID = 8,
                            Waterproof = true,
                            WireMaterial = "Dây da chính hãng kèm 1 dây Silver gold ( vàng trắng )"
                        });
                });

            modelBuilder.Entity("WatchManageStore.Models.Post", b =>
                {
                    b.Property<int>("PostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Image1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("PostId");

                    b.HasIndex("Id");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            PostId = 1,
                            Content = "Nhân ngày Quốc tế phụ nũ 08/03 Đăng Quang Watch đã cập nhật hàng ngàn mẫu đồng hồ mới nhất, trend nhất dành riêng cho phái đẹp cùng chương trình khuyến mại đặc biệt: Giảm giá lên tới 30% và hoàn tiền 100% giá trị hóa đơn mua hàngĐồng hồ đeo tay chính là món phụ kiện giúp chị em phụ nữ hiện đại thể hiện phong cách thời trang và vẻ ngoài thanh lịch của mình, hơn nữa còn là vật dụng vô cùng hữu ích và cần thiết trong đời sống hàng ngày.Đồng hồ là biểu trưng cho thời gian. Khi làm quà tặng cho người mà mình trân quý, đồng hồ mang thông điệp tình cảm người tặng dành cho họ là bất diệt, không phai tàn theo thời gian.Nhiều mẫu đồng hồ đẹp có thể làm quà tặng 08/03 ý nghĩa đang có sẵn tại hệ thống gần 100 showroom Đăng Quang Watch.Trong đó, một số thương hiệu đang được nhiều người yêu thích như Diamond D, Aries Gold, Epos, Atlantic, Bruno Sohnle Glashutte, Citizen, Q&Q... Với chế độ bảo hành quốc tế, xuất hoá đơn đỏ, giấy tờ hải quan chứng minh nguồn gốc xuất xứ sản phẩm, khách hàng hoàn toàn có thể yên tâm sử dụng cũng như tin tưởng lựa chọn làm món quà tặng ý nghĩa cho người thân yêu.Ngoài các sản phẩm đồng hồ với thiết kế sang trọng, tinh tế, trẻ trung khách hàng có thể lựa chọn quà tặng là những sản phẩm kính mắt đến từ Kính Mắt Đăng Quang với thiết kế vô cùng năng động và cá tính.Kể từ ngày 01/03 đến 15/03/2022 Đăng Quang Watch tặng ngay ưu đãi giảm giá lên tới 30% cùng cơ hội quay số may mắn hoàn tiền 100% giá trị hóa đơn khi mua sắm đồng hồ trong dịp này. Để tham gia chương trình, khi mua hàng khách hàng chỉ cần điền đầy đủ thông tin vào hóa đơn. Trong đó, mã số tham dự quay giải chính là 4 số cuối số điện thoại của khách hàng. Chương trình sẽ dùng kết quả xổ số miền Bắc quay thưởng ngày 16/03/2022 làm căn cứ trao giải. Khách hàng may mắn 4 số cuối điện thoại cuối trùng với giải đặc biệt sẽ trở thành khách hàng may mắn nhất được hoàn lại 100% giá trị hóa đơn.",
                            CreateOn = new DateTime(2022, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Image1 = "noi-bat-movado.png",
                            ModifyDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = true,
                            Title = "Bùng nổ ưu đãi 08/03 : Giảm giá lên tới 30% và hoàn tiền 100% giá trị hóa đơn tại Đăng Quang Watch",
                            UserId = "408aa945-3d84-4421-8342-7269ec64d949"
                        },
                        new
                        {
                            PostId = 2,
                            Content = "Mãnh Hổ được xem là biểu tượng của sức mạnh, quyền uy, sự thăng tiến trong học hành và kinh doanh. Trong dân gian con Hổ còn được coi là linh vật giám hộ hướng Tây, đầy uy lực, linh thiêng và được thờ phụng rất nhiều, bảo vệ cho gia chủ, đảm bảo tiền tài, sức khoẻ cho các thành viên trong gia đình.Đồng hồ Mãnh Hổ PA2022 phiên bản giới hạn chỉ 100 chiếc trên toàn cầu. Với mặt số được trang trí nổi bật biểu tượng con Hổ dũng mãnh - linh vật của năm. Thiết kế bộ kim màu vàng sang đẹp mắt và phần vò gắn kim cương nhân tạo tăng lên sự quyền lực, phú quý cho sản phẩm này.Đồng hồ Philippe Auguste là thương hiệu xuất xứ Châu Âu và được Đăng Quang Watch phân phối độc quyền tại Việt Nam. Với mã sản phẩm PA2022 phiên bản giới hạn toàn cầu chỉ có 100 chiếc là một thiết kế đặc biệt dành riêng cho năm 2022. Được trang bị mặt kính Saphire với khả năng chống xước tốt kết hợp chất liệu vỏ thép không gỉ được mạ công nghệ PVD tiên tiến.",
                            CreateOn = new DateTime(2022, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Image1 = "noi-bat-versace.png",
                            ModifyDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = true,
                            Title = "ĐỒNG HỒ MÃNH HỔPHIÊN BẢN GIỚI HẠN - CHÀO ĐÓN NHÂM DẦN",
                            UserId = "408aa945-3d84-4421-8342-7269ec64d949"
                        },
                        new
                        {
                            PostId = 3,
                            Content = "Bắt nguồn từ câu chuyện về hoàng đế Philippe Auguste (Philipe II) - Quốc vương đầu tiên của nước Pháp với tham vọng gây dựng đế chế cho riêng mình. Ông đã trải qua hơn hai thập kỷ chiến đấu, mở rộng lãnh thổ nhằm củng cố vương vị, quyền lực và sức mạnh. Nhờ tài trí, mưu lược, Philippe Auguste đã biến Pháp từ một đất nước phong kiến nhỏ bé trở thành quốc gia thịnh vượng và hùng mạnh ở châu Âu.Đồng hồ Philippe Auguste là biểu tượng của tham vọng, bản lĩnh, sức mạnh và khát khao thành công, khẳng định giá trị bản thân, những yếu tố không thể thiếu của người đàn ông trong cuộc sống hiện đại.Dòng sản phẩm Philippe Auguste định hướng dành riêng cho khách hàng nam giới yêu thích đồng hồ với phân khúc giá trung bình từ 4 - 20 triệu đồng. Với những thiết kế hợp “gu” khách hàng, Philippe Auguste ngày càng khẳng định vị trí thương hiệu của mình.Mùa đông năm nay, Philippe Auguste đã cho ra mắt BST mới với sự mới mẻ hơn về thiết kế.Không chỉ giữ nguyên những nét đẹp cổ điển tinh tế, với BST lần này Philippe Auguste đã ra mắt rất nhiều mẫu sản phẩm đồng hồ pin với phong cách năng động hơn,thể thao hơn cho các anh trai.",
                            CreateOn = new DateTime(2021, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Image1 = "noi-bat-zenith.png",
                            ModifyDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = true,
                            Title = "Phillipe Auguste – Đẳng cấp quý ông Châu Âu",
                            UserId = "408aa945-3d84-4421-8342-7269ec64d949"
                        },
                        new
                        {
                            PostId = 4,
                            Content = "Epos nằm trong trong top 10 hãng đồng hồ độc lập uy tín nhất trong ngành đồng hồ Thụy Sĩ. Những chiếc đồng hồ được sản xuất thủ công với bí quyết lâu đời đã tạo ra những chiếc đồng hồ tuyệt vời.Trong những năm 80 của thế kỷ trước, khi mà ngành công nghiệp đồng hồ Thụy Sĩ truyền thống trở nên bế tắc vì không thể cạnh tranh nổi với những đồng hồ Quartz đang làm mưa làm gió trên thị trường. Peter Hofer - một chuyên gia đầy kinh nghiệm trong sản xuất đồng hồ Thụy Sĩ, ông và vợ ông Erna quyết định thành lập công ty của riêng mình năm 1983: Montres EPOS SA. Tài sản chính của họ là một niềm đam mê đối với đồng hồ cơ khí và một bí quyết kỹ thuật trong lĩnh vực này.Ngay từ đầu, EPOS đã là một thương hiệu cơ khí với những đổi mới thú vị. Trong những năm qua, EPOS vẫn trung thành với lựa chọn của mình, phát triển bộ sưu tập đồng hồ tuyệt đẹp kết hợp các cơ hấp dẫn.Đạt được danh tiếng trên toàn thế giới qua nhiều thế kỷ,nhờ tinh thần tiên phong và ý nghĩ độc đáo trong sự gia công hoàn hảo của đồng hồ.Đồng hồ Thụy Sỹ EPOS đã trở thành một người giám hộ,là thước đo của các giá trị truyền thống và các tiêu chuẩn cao.",
                            CreateOn = new DateTime(2021, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Image1 = "onghokimnguu2.jpg",
                            ModifyDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = true,
                            Title = "EPOS - Tinh hoa nghệ thuật của đồng hồ Thụy Sỹ",
                            UserId = "408aa945-3d84-4421-8342-7269ec64d949"
                        },
                        new
                        {
                            PostId = 5,
                            Content = "Thông thường các dòng đồng hồ Automatic vẫn được tích hợp thêm chức năng Handwinding vì thế những thông tin dưới đây sẽ là tổng hợp cả hai dòng đồng hồ trên. Có khá nhiều cách để lên dây cót cho đồng hồ Automatic từ đơn giản đến phức tạp. Không để anh em phải chờ lâu thêm nữa, dưới đây sẽ là những thông tin hướng dẫn lên dây cót đồng hồ.Chuyển động cánh tay đeo đồng hồ Khá đơn giản đúng không nào. Tuy nhiên, nhiều anh em lại nghĩ cánh tay phải chuyển động liên tục thì mới có thể lên dây cót đồng hồ nhưng không, sự tinh xảo trong thiết kế sẽ giúp đồng hồ lên dây cót khi anh em hoạt động thương ngày. Khi anh em đeo đồng hồ và hoạt động bình thường thì chiếc đồng hồ của anh em đã được nạp năng lượng và cho sự hoạt động ổn định nhất. Còn một lời khuyên nữa cho anh em đó chính là không nên vận động quá mạnh ví dụ khi chơi bóng đá, cầu lông, tenis,… vì những va đập có thể ảnh hưởng đến khả năng lên dây cót của đồng hồ.Để đảm bảo chiếc đồng hồ Automatic hoạt động bình thường ( ngay cả vào ban đêm khi không sử dụng ) thì anh em nên đeo ít nhất 8 tiếng 1 ngày.Lên dây cót đồng hồ bằng núm vặn Như đã nói,đồng hồ cơ Automatic hiện nay còn được tích hợp thêm chức năng lên dây cót bằng tay.Đối với những dòng đồng hồ như thế này,anh em chỉ việc tác động một lực vừa để vặn núm điều chỉnh(không nên vặn quá căng).Nếu tỉ mỉ thì anh em có thể vặn từ 15 đến 20 vòng là đẹp nhất.",
                            CreateOn = new DateTime(2021, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Image1 = "noi-bat-versace.png",
                            ModifyDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = true,
                            Title = "Hướng dẫn cách chỉnh dây cót đồng hồ automatic",
                            UserId = "408aa945-3d84-4421-8342-7269ec64d949"
                        });
                });

            modelBuilder.Entity("WatchManageStore.Models.RateAccount", b =>
                {
                    b.Property<int>("RateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreateOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PostId")
                        .HasColumnType("int");

                    b.Property<double>("Rate")
                        .HasColumnType("float");

                    b.Property<int?>("StoreId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("WatchId")
                        .HasColumnType("int");

                    b.HasKey("RateId");

                    b.HasIndex("Id");

                    b.HasIndex("PostId");

                    b.HasIndex("StoreId");

                    b.HasIndex("WatchId");

                    b.ToTable("RateAccounts");

                    b.HasData(
                        new
                        {
                            RateId = 1,
                            CreateOn = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifyDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 2.0,
                            StoreId = 1,
                            UserId = "408aa945-3d84-4421-8342-7269ec64d949"
                        },
                        new
                        {
                            RateId = 2,
                            CreateOn = new DateTime(2023, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifyDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 5.0,
                            StoreId = 2,
                            UserId = "408aa945-3d84-4421-8342-7269ec64d949"
                        },
                        new
                        {
                            RateId = 3,
                            CreateOn = new DateTime(2021, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifyDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 3.0,
                            UserId = "408aa945-3d84-4421-8342-7269ec64d949",
                            WatchId = 1
                        },
                        new
                        {
                            RateId = 4,
                            CreateOn = new DateTime(2021, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifyDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 2.0,
                            UserId = "408aa945-3d84-4421-8342-7269ec64d949",
                            WatchId = 2
                        },
                        new
                        {
                            RateId = 5,
                            CreateOn = new DateTime(2021, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifyDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 4.0,
                            UserId = "408aa945-3d84-4421-8342-7269ec64d949",
                            WatchId = 3
                        },
                        new
                        {
                            RateId = 6,
                            CreateOn = new DateTime(2021, 12, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifyDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PostId = 1,
                            Rate = 3.0,
                            UserId = "408aa945-3d84-4421-8342-7269ec64d949"
                        },
                        new
                        {
                            RateId = 7,
                            CreateOn = new DateTime(2021, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifyDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PostId = 2,
                            Rate = 2.0,
                            UserId = "408aa945-3d84-4421-8342-7269ec64d949"
                        },
                        new
                        {
                            RateId = 8,
                            CreateOn = new DateTime(2021, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifyDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PostId = 3,
                            Rate = 3.0,
                            UserId = "408aa945-3d84-4421-8342-7269ec64d949"
                        },
                        new
                        {
                            RateId = 9,
                            CreateOn = new DateTime(2021, 12, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifyDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PostId = 4,
                            Rate = 3.0,
                            UserId = "408aa945-3d84-4421-8342-7269ec64d949"
                        },
                        new
                        {
                            RateId = 10,
                            CreateOn = new DateTime(2021, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifyDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 4.0,
                            UserId = "408aa945-3d84-4421-8342-7269ec64d949",
                            WatchId = 4
                        },
                        new
                        {
                            RateId = 11,
                            CreateOn = new DateTime(2021, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifyDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 4.0,
                            UserId = "408aa945-3d84-4421-8342-7269ec64d949",
                            WatchId = 5
                        },
                        new
                        {
                            RateId = 12,
                            CreateOn = new DateTime(2021, 12, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifyDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PostId = 5,
                            Rate = 2.0,
                            UserId = "408aa945-3d84-4421-8342-7269ec64d949"
                        });
                });

            modelBuilder.Entity("WatchManageStore.Models.Store", b =>
                {
                    b.Property<int>("StoreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<string>("StoreName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("StoreId");

                    b.ToTable("Stores");

                    b.HasData(
                        new
                        {
                            StoreId = 1,
                            Address = "Tran Dang Ninh, Cau Giay, HN",
                            CreateOn = new DateTime(2021, 12, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Nhà phân phối độc quyền các thương hiệu đồng hồ, kính mắt, bút ký nổi tiếng thế giới: Epos Swiss, Atlantic Swiss, Diamond D, Philippe Auguste, Jacques Lemans, Citizen, Aries Gold, dây da đồng hồ, dây đồng hồ đeo tay....",
                            Image = "Dangquang.jpg",
                            ModifyDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Phone = "18006005",
                            Status = true,
                            StoreName = "Dang Quang Watch"
                        },
                        new
                        {
                            StoreId = 2,
                            Address = "Ho Chi Minh",
                            CreateOn = new DateTime(2020, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Đồng Hồ Hải Triều, hệ thống đồng hồ chính hãng tại Việt Nam. Nơi phân phối 15.000+ mẫu đồng hồ mới nhất từ hơn 22 thương hiệu nổi tiếng thế giới. Trải nghiệm mua sắm ngay hôm nay",
                            Image = "haitrieu.jpg",
                            ModifyDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Phone = "19006777",
                            Status = true,
                            StoreName = "Hai Trieu Watch"
                        },
                        new
                        {
                            StoreId = 3,
                            Address = "Ha Noi",
                            CreateOn = new DateTime(2018, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Khởi đầu với một cửa hàng nằm trên phố Tuệ Tĩnh, Hà Nội từ năm 2003, vượt qua nhiều thách thức gian nan, đến nay Galle Watch đã có thể hoàn toàn tự hào khi trở thành hệ thống phân phối đồng hồ hàng đầu Việt Nam. Với mong muốn mang lại cho khách hàng những sản phẩm chính hãng cùng dịch vụ sau bán hàng đạt tiêu chuẩn 4 sao, Galle Watch đang ngày càng nỗ lực để hoàn thiện và nâng cao chất lượng dịch vụ của mình.",
                            Image = "gallewatch.jpg",
                            ModifyDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Phone = "19006000",
                            Status = true,
                            StoreName = "Galle Watch"
                        });
                });

            modelBuilder.Entity("WatchManageStore.Models.Watch", b =>
                {
                    b.Property<int>("WatchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("InsuranceDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<int>("StoreId")
                        .HasColumnType("int");

                    b.Property<string>("WatchName")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("WatchId");

                    b.HasIndex("BrandId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("StoreId");

                    b.ToTable("Watchs");

                    b.HasData(
                        new
                        {
                            WatchId = 1,
                            BrandId = 1,
                            CategoryId = 2,
                            CreateOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Image = "bovet6.jpg",
                            InsuranceDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifyDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 450000000.0,
                            Status = true,
                            StoreId = 1,
                            WatchName = "Đồng hồ cao cấp Bovet AS36001SD12"
                        },
                        new
                        {
                            WatchId = 2,
                            BrandId = 2,
                            CategoryId = 1,
                            CreateOn = new DateTime(2021, 12, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Image = "dong-ho-nam1.jpg",
                            InsuranceDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifyDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 50000000.0,
                            Status = true,
                            StoreId = 1,
                            WatchName = "ĐỒNG HỒ PHILIPPE AUGUSTE PA2022"
                        },
                        new
                        {
                            WatchId = 3,
                            BrandId = 3,
                            CategoryId = 1,
                            CreateOn = new DateTime(2021, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Image = "dong-ho-nam2.jpg",
                            InsuranceDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifyDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 23000000.0,
                            Status = true,
                            StoreId = 2,
                            WatchName = "Đồng hồ Aries Gold AG-L5033Z G-W"
                        },
                        new
                        {
                            WatchId = 4,
                            BrandId = 4,
                            CategoryId = 3,
                            CreateOn = new DateTime(2021, 10, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Image = "dong-ho-nam3.jpg",
                            InsuranceDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifyDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 300000000.0,
                            Status = true,
                            StoreId = 3,
                            WatchName = "Đồng Hồ Hublot Classic Fusion Chronograph Titanium Automatic Black Dial Men's Watch"
                        },
                        new
                        {
                            WatchId = 5,
                            BrandId = 5,
                            CategoryId = 1,
                            CreateOn = new DateTime(2021, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Image = "dong-ho-nam4.jpg",
                            InsuranceDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifyDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 25000000.0,
                            Status = true,
                            StoreId = 3,
                            WatchName = "Đồng hồ Bruno sohnle 17-13153-241"
                        },
                        new
                        {
                            WatchId = 6,
                            BrandId = 6,
                            CategoryId = 3,
                            CreateOn = new DateTime(2021, 5, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Image = "QQdoi.jpg",
                            InsuranceDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifyDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 40000000.0,
                            Status = true,
                            StoreId = 2,
                            WatchName = "Đồng hồ Q&Q QQ-S278J102Y + QQ-S279J102Y"
                        },
                        new
                        {
                            WatchId = 7,
                            BrandId = 7,
                            CategoryId = 1,
                            CreateOn = new DateTime(2021, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Image = "dong-ho-nam5.jpg",
                            InsuranceDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifyDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 15000000.0,
                            Status = true,
                            StoreId = 3,
                            WatchName = "ĐỒNG HỒ PHILIPPE AUGUSTE PA-555.2"
                        },
                        new
                        {
                            WatchId = 8,
                            BrandId = 8,
                            CategoryId = 1,
                            CreateOn = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Image = "dong-ho-nam6.jpg",
                            InsuranceDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifyDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 65000000.0,
                            Status = true,
                            StoreId = 2,
                            WatchName = "Đồng hồ Jacques Lemans JL - 1 - 1830A"
                        });
                });

            modelBuilder.Entity("WatchManageStore.Models.Account", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("LastName")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasDiscriminator().HasValue("Account");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WatchManageStore.Models.Comment", b =>
                {
                    b.HasOne("WatchManageStore.Models.Account", "Accounts")
                        .WithMany("Comments")
                        .HasForeignKey("Id");

                    b.HasOne("WatchManageStore.Models.Post", "Post")
                        .WithMany("Comments")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WatchManageStore.Models.Watch", "Watch")
                        .WithMany()
                        .HasForeignKey("WatchId");

                    b.Navigation("Accounts");

                    b.Navigation("Post");

                    b.Navigation("Watch");
                });

            modelBuilder.Entity("WatchManageStore.Models.DetailWatch", b =>
                {
                    b.HasOne("WatchManageStore.Models.Watch", "Watch")
                        .WithOne("DetailWatch")
                        .HasForeignKey("WatchManageStore.Models.DetailWatch", "WatchID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Watch");
                });

            modelBuilder.Entity("WatchManageStore.Models.Post", b =>
                {
                    b.HasOne("WatchManageStore.Models.Account", "Accounts")
                        .WithMany("Posts")
                        .HasForeignKey("Id");

                    b.Navigation("Accounts");
                });

            modelBuilder.Entity("WatchManageStore.Models.RateAccount", b =>
                {
                    b.HasOne("WatchManageStore.Models.Account", "Accounts")
                        .WithMany("RateAccounts")
                        .HasForeignKey("Id");

                    b.HasOne("WatchManageStore.Models.Post", "Post")
                        .WithMany("RateAccounts")
                        .HasForeignKey("PostId");

                    b.HasOne("WatchManageStore.Models.Store", "Store")
                        .WithMany("RateAccounts")
                        .HasForeignKey("StoreId");

                    b.HasOne("WatchManageStore.Models.Watch", "Watch")
                        .WithMany("RateAccounts")
                        .HasForeignKey("WatchId");

                    b.Navigation("Accounts");

                    b.Navigation("Post");

                    b.Navigation("Store");

                    b.Navigation("Watch");
                });

            modelBuilder.Entity("WatchManageStore.Models.Watch", b =>
                {
                    b.HasOne("WatchManageStore.Models.Brand", "Brands")
                        .WithMany()
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WatchManageStore.Models.Category", "Categories")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WatchManageStore.Models.Store", "Store")
                        .WithMany("Watches")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brands");

                    b.Navigation("Categories");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("WatchManageStore.Models.Post", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("RateAccounts");
                });

            modelBuilder.Entity("WatchManageStore.Models.Store", b =>
                {
                    b.Navigation("RateAccounts");

                    b.Navigation("Watches");
                });

            modelBuilder.Entity("WatchManageStore.Models.Watch", b =>
                {
                    b.Navigation("DetailWatch");

                    b.Navigation("RateAccounts");
                });

            modelBuilder.Entity("WatchManageStore.Models.Account", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Posts");

                    b.Navigation("RateAccounts");
                });
#pragma warning restore 612, 618
        }
    }
}
